import Head from "next/head";
import {
  AiFillFacebook,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import robert from "../public/robert.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Web Developer Robert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">

          <nav className="py-10 mb-12 flex justify-around dark:text-white">

            <h1 className="text-xl mr-2">Developed by:</h1>
            
            <ul className="flex items-center">

              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer hover:scale-110 hover:transition-all text-2xl"
                />
              </li>

              <li className="cursor-pointer hover:scale-110 hover:transition-all">
                <a
                  className="bg-gradient-to-r from-red-700 text- to-orange-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                  href="#"
                >
                  Resume
                </a>
              </li>

            </ul>

          </nav>

          <div className="text-center p-10 py-10">

            <h2 className="text-5xl py-2 text-teal-500 font-medium dark:text-orange-400 md:text-6xl">
              Robert Firanji
            </h2>

            <h3 className="text-2xl py-2 font-medium dark:text-white md:text-3xl">
              Web Developer
            </h3>

            <p className="font-medium py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>

            <div className="text-5xl flex justify-center gap-3 py-1 text-gray-600 dark:text-gray-400  md:gap-16 lg:gap-16">

              <AiFillFacebook className="cursor-pointer hover:scale-110 hover:transition-all hover:bg-gradient-to-r from-red-700 text- to-orange-500 rounded-md" />

              <AiFillLinkedin className="cursor-pointer hover:scale-110 hover:transition-all hover:bg-gradient-to-l from-red-700 text- to-orange-500 rounded-md" />

              <AiFillInstagram className="cursor-pointer hover:scale-110 hover:transition-all hover:bg-gradient-to-b from-red-700 text- to-orange-500 rounded-md" />

            </div>

            <div className="mx-auto bg-gradient-to-b from-orange-400 rounded-full w-48 h-48 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={robert} layout="fill" objectFit="cover" />

            </div>

          </div>

        </section>

        <section>
          <div>
            <h3 className="text-3xl font-medium py-3 dark:text-white ">Services I offer</h3>

            <p className="font-medium py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>

            <p className="font-medium py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>

          </div>

          <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 bg-gradient-to-r from-cyan-400 to-blue-500 cursor-pointer hover:bg-gradient-to-l">

              <Image src={design} width={100} height={100} />
              
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>

              <p className="text-gray-800 py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>

              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 bg-gradient-to-l from-cyan-400 to-green-500 cursor-pointer hover:bg-gradient-to-b">

              <Image src={code} width={100} height={100} />

              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>

              <p className="text-gray-800 py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>

              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>

            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 bg-gradient-to-b from-orange-300 to-red-500 pointer hover:bg-gradient-to-t">

              <Image src={consulting} width={100} height={100} />

              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>

              <p className="text-gray-800 py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>

              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>

              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>

            </div>

          </div>

        </section>

        <section className="py-10">

          <div>

            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>

            <p className="font-medium py-2 leading-8 text-gray-800 dark:text-gray-200">

              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>

            <p className="font-medium py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>

          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web1}
              />

            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web2}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web3}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web4}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web5}
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover cursor-pointer hover:scale-105 hover:transition-all"
                width={"100%"}
                height={"100%"}
                src={web6}
              />
            </div>

          </div>

        </section>

      </main>
      
    </div>
  );
}
